trigger: none

resources:
- repo: self

variables:
  ACR_NAME: '********'
  ACR_REPOSITORY: '********'
  ACR_TOKEN: '***********'
  ACR_TOKEN_NAME: '********'

pool:
  name: 'azurevm'
  demands:
  - 'agent.name -equals computercp'

jobs:
- job: BuildAndPush
  displayName: Build and Push Docker Image
  steps:
  - script: |
      echo "Optimizing Git configuration..."
      git config --global core.packedGitLimit 256m
      git config --global core.packedGitWindowSize 256m
      git config --global pack.deltaCacheSize 256m
      git config --global pack.packSizeLimit 256m
      git config --global pack.windowMemory 256m
    displayName: 'Optimize Git Configuration'
    
  - script: |
      echo "Logging into Azure Container Registry..."
      echo $(ACR_TOKEN) | docker login $(ACR_NAME) -u $(ACR_TOKEN_NAME) --password-stdin
    displayName: 'Login to ACR'
    
  - script: |
      echo "Building the Docker image..."
      docker build -t $(ACR_NAME)/$(ACR_REPOSITORY):latest -f Dockerfile .
    displayName: 'Build Docker Image'
    
  - script: |
      echo "Pushing the Docker image to ACR..."
      docker push $(ACR_NAME)/$(ACR_REPOSITORY):latest
    displayName: 'Push Docker Image'
    
  - script: |
      echo "Docker image successfully pushed to Azure Container Registry."
    displayName: 'Success Message'
